Update github-actions-demo.yml

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -1,18 +1,56 @@
-name: GitHub Actions Demo
-run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
-on: [push]
+name: lint
+
+on:
+  push:
+    branches:
+      - main
+      - dev
+  pull_request:
+    branches:
+      - main
+      - dev
+
+env:
+  WORKDIR: "."
+  RUFF_OUTPUT_FORMAT: github
+  UV_FROZEN: "true"
+  UV_VERSION: "0.5.25"
 jobs:
-  Explore-GitHub-Actions:
+  build:
+    name: "Lint on push or PR"
     runs-on: ubuntu-latest
+    timeout-minutes: 20
+
     steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
-      - name: Check out repository code
+      - name: Checkout code
         uses: actions/checkout@v4
-      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
-      - name: List files in the repository
+
+      - name: Install uv and set the Python version
+        uses: astral-sh/setup-uv@v5
+        with:
+          version: ${{ env.UV_VERSION }}
+          python-version: "3.10"
+
+      - name: Install dependencies
+        run: uv sync --group lint --group typing
+
+      - name: Run Lint on package
         run: |
-          ls ${{ github.workspace }}
-      - run: echo "🍏 This job's status is ${{ job.status }}."
+          if make lint_package; then
+            echo "Lint passed ✅"
+          else
+            echo "Lint failed ❌"
+            exit 1
+          fi
+
+      - name: Install unit test dependencies
+        run: uv sync --inexact --group test
+
+      - name: Run Lint on tests
+        run: |
+          if make lint_tests; then
+            echo "Test lint passed ✅"
+          else
+            echo "Test lint failed ❌"
+            exit 1
+          fi
